SET XACT_ABORT ON;
BEGIN TRANSACTION;

/* 5종 주요장비 기본정보의 점검주기(개월). 기존 데이터에는 기본값을 적용한다. */
IF COL_LENGTH('dbo.VCB_BASICINFO', 'REGULAR_INSPECTION_CYCLE_MONTHS') IS NULL
    ALTER TABLE dbo.VCB_BASICINFO ADD REGULAR_INSPECTION_CYCLE_MONTHS INT NOT NULL
        CONSTRAINT DF_VCB_BASICINFO_REGULAR_CYCLE DEFAULT (3) WITH VALUES;
IF COL_LENGTH('dbo.VCB_BASICINFO', 'PRECISION_INSPECTION_CYCLE_MONTHS') IS NULL
    ALTER TABLE dbo.VCB_BASICINFO ADD PRECISION_INSPECTION_CYCLE_MONTHS INT NOT NULL
        CONSTRAINT DF_VCB_BASICINFO_PRECISION_CYCLE DEFAULT (12) WITH VALUES;

IF COL_LENGTH('dbo.ITR_BASICINFO', 'REGULAR_INSPECTION_CYCLE_MONTHS') IS NULL
    ALTER TABLE dbo.ITR_BASICINFO ADD REGULAR_INSPECTION_CYCLE_MONTHS INT NOT NULL
        CONSTRAINT DF_ITR_BASICINFO_REGULAR_CYCLE DEFAULT (3) WITH VALUES;
IF COL_LENGTH('dbo.ITR_BASICINFO', 'PRECISION_INSPECTION_CYCLE_MONTHS') IS NULL
    ALTER TABLE dbo.ITR_BASICINFO ADD PRECISION_INSPECTION_CYCLE_MONTHS INT NOT NULL
        CONSTRAINT DF_ITR_BASICINFO_PRECISION_CYCLE DEFAULT (12) WITH VALUES;

IF COL_LENGTH('dbo.DCCB_BASICINFO', 'REGULAR_INSPECTION_CYCLE_MONTHS') IS NULL
    ALTER TABLE dbo.DCCB_BASICINFO ADD REGULAR_INSPECTION_CYCLE_MONTHS INT NOT NULL
        CONSTRAINT DF_DCCB_BASICINFO_REGULAR_CYCLE DEFAULT (3) WITH VALUES;
IF COL_LENGTH('dbo.DCCB_BASICINFO', 'PRECISION_INSPECTION_CYCLE_MONTHS') IS NULL
    ALTER TABLE dbo.DCCB_BASICINFO ADD PRECISION_INSPECTION_CYCLE_MONTHS INT NOT NULL
        CONSTRAINT DF_DCCB_BASICINFO_PRECISION_CYCLE DEFAULT (12) WITH VALUES;

IF COL_LENGTH('dbo.DCCABLE_BASICINFO', 'REGULAR_INSPECTION_CYCLE_MONTHS') IS NULL
    ALTER TABLE dbo.DCCABLE_BASICINFO ADD REGULAR_INSPECTION_CYCLE_MONTHS INT NOT NULL
        CONSTRAINT DF_DCCABLE_BASICINFO_REGULAR_CYCLE DEFAULT (3) WITH VALUES;
IF COL_LENGTH('dbo.DCCABLE_BASICINFO', 'PRECISION_INSPECTION_CYCLE_MONTHS') IS NULL
    ALTER TABLE dbo.DCCABLE_BASICINFO ADD PRECISION_INSPECTION_CYCLE_MONTHS INT NOT NULL
        CONSTRAINT DF_DCCABLE_BASICINFO_PRECISION_CYCLE DEFAULT (12) WITH VALUES;

IF COL_LENGTH('dbo.SUBMODULE_BASICINFO', 'REGULAR_INSPECTION_CYCLE_MONTHS') IS NULL
    ALTER TABLE dbo.SUBMODULE_BASICINFO ADD REGULAR_INSPECTION_CYCLE_MONTHS INT NOT NULL
        CONSTRAINT DF_SUBMODULE_BASICINFO_REGULAR_CYCLE DEFAULT (3) WITH VALUES;
IF COL_LENGTH('dbo.SUBMODULE_BASICINFO', 'PRECISION_INSPECTION_CYCLE_MONTHS') IS NULL
    ALTER TABLE dbo.SUBMODULE_BASICINFO ADD PRECISION_INSPECTION_CYCLE_MONTHS INT NOT NULL
        CONSTRAINT DF_SUBMODULE_BASICINFO_PRECISION_CYCLE DEFAULT (12) WITH VALUES;

COMMIT TRANSACTION;
