SET XACT_ABORT ON;
BEGIN TRANSACTION;

DECLARE @NextValue BIGINT;
DECLARE @Sql NVARCHAR(MAX);

IF OBJECT_ID('dbo.SEQ_SPARE_ID', 'SO') IS NULL
BEGIN
    SELECT @NextValue = ISNULL(MAX(SPARE_ID), 0) + 1 FROM dbo.TB_SPARE_PART;
    SET @Sql = N'CREATE SEQUENCE dbo.SEQ_SPARE_ID AS INT START WITH '
        + CONVERT(NVARCHAR(30), @NextValue) + N' INCREMENT BY 1;';
    EXEC sys.sp_executesql @Sql;
END;

IF OBJECT_ID('dbo.SEQ_SPARE_ASSET_MAP_ID', 'SO') IS NULL
BEGIN
    SELECT @NextValue = ISNULL(MAX(SPARE_ASSET_MAP_ID), 0) + 1 FROM dbo.TB_SPARE_ASSET_MAP;
    SET @Sql = N'CREATE SEQUENCE dbo.SEQ_SPARE_ASSET_MAP_ID AS INT START WITH '
        + CONVERT(NVARCHAR(30), @NextValue) + N' INCREMENT BY 1;';
    EXEC sys.sp_executesql @Sql;
END;

IF OBJECT_ID('dbo.SEQ_INV_ID', 'SO') IS NULL
BEGIN
    SELECT @NextValue = ISNULL(MAX(INV_ID), 0) + 1 FROM dbo.TB_INVENTORY;
    SET @Sql = N'CREATE SEQUENCE dbo.SEQ_INV_ID AS INT START WITH '
        + CONVERT(NVARCHAR(30), @NextValue) + N' INCREMENT BY 1;';
    EXEC sys.sp_executesql @Sql;
END;

IF OBJECT_ID('dbo.SEQ_PROC_ID', 'SO') IS NULL
BEGIN
    SELECT @NextValue = ISNULL(MAX(PROC_ID), 0) + 1 FROM dbo.TB_PROCUREMENT;
    SET @Sql = N'CREATE SEQUENCE dbo.SEQ_PROC_ID AS INT START WITH '
        + CONVERT(NVARCHAR(30), @NextValue) + N' INCREMENT BY 1;';
    EXEC sys.sp_executesql @Sql;
END;

IF OBJECT_ID('dbo.SEQ_COST_ID', 'SO') IS NULL
BEGIN
    SELECT @NextValue = ISNULL(MAX(COST_ID), 0) + 1 FROM dbo.TB_COST_MANAGEMENT;
    SET @Sql = N'CREATE SEQUENCE dbo.SEQ_COST_ID AS INT START WITH '
        + CONVERT(NVARCHAR(30), @NextValue) + N' INCREMENT BY 1;';
    EXEC sys.sp_executesql @Sql;
END;

INSERT INTO dbo.TB_INVENTORY
(
    INV_ID,
    SPARE_ID,
    CURRENT_QTY,
    SAFETY_STOCK,
    EOQ,
    REORDER_POINT,
    LAST_UPDATED
)
SELECT
    NEXT VALUE FOR dbo.SEQ_INV_ID,
    S.SPARE_ID,
    0,
    0,
    0,
    0,
    GETDATE()
FROM dbo.TB_SPARE_PART S
WHERE NOT EXISTS
(
    SELECT 1
    FROM dbo.TB_INVENTORY I
    WHERE I.SPARE_ID = S.SPARE_ID
);

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.TB_SPARE_PART')
      AND name = 'UX_TB_SPARE_PART_PART_NUMBER'
)
BEGIN
    CREATE UNIQUE INDEX UX_TB_SPARE_PART_PART_NUMBER
        ON dbo.TB_SPARE_PART(PART_NUMBER)
        WHERE PART_NUMBER IS NOT NULL;
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.TB_INVENTORY')
      AND name = 'UX_TB_INVENTORY_SPARE_ID'
)
BEGIN
    CREATE UNIQUE INDEX UX_TB_INVENTORY_SPARE_ID
        ON dbo.TB_INVENTORY(SPARE_ID);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.TB_SPARE_ASSET_MAP')
      AND name = 'UX_TB_SPARE_ASSET_MAP_SPARE_ASSET_TYPE'
)
BEGIN
    CREATE UNIQUE INDEX UX_TB_SPARE_ASSET_MAP_SPARE_ASSET_TYPE
        ON dbo.TB_SPARE_ASSET_MAP(SPARE_ID, ASSET_TYPE_ID);
END;

COMMIT TRANSACTION;
