SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH('dbo.ITR_CHK1', 'CHK1_THERMAL_TEMPERATURE') IS NULL
BEGIN
    ALTER TABLE dbo.ITR_CHK1
        ADD CHK1_THERMAL_TEMPERATURE INT NOT NULL
            CONSTRAINT DF_ITR_CHK1_THERMAL_TEMPERATURE DEFAULT (1);
END;

IF COL_LENGTH('dbo.VCB_CHK', 'CHK_THERMALTEMPERATURE') IS NULL
BEGIN
    ALTER TABLE dbo.VCB_CHK
        ADD CHK_THERMALTEMPERATURE INT NOT NULL
            CONSTRAINT DF_VCB_CHK_THERMALTEMPERATURE DEFAULT (1);
END;

COMMIT TRANSACTION;
